apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequence-bank-app
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: sequence-bank-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sequence-bank-app
    spec:
      containers:
        - name: sequence-bank-container
          image: {{IMAGE_NAME}}
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://sequence-bank-db:5432/sequence-bank
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sequence-bank-db-credentials
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sequence-bank-db-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /health/live
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sequence-bank-service
  namespace: {{NAMESPACE}}
  labels:
    app: sequence-bank-service
spec:
  type: ClusterIP
  ports:
    - port: {{SERVICE_PORT}}
      protocol: TCP
      targetPort: app-port
  selector:
    app: sequence-bank-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sequence-bank
  namespace: {{NAMESPACE}}
spec:
  rules:
    - host: sequence-bank.mydna.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sequence-bank-service
                port:
                  number: {{SERVICE_PORT}}