apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequence-bank-db-app
  namespace: mydnacodes
spec:
  selector:
    matchLabels:
      app: sequence-bank-db-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sequence-bank-db-app
    spec:
      containers:
        - name: postgres
          image: postgres:12
          ports:
            - name: db-port
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sequence-bank
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sequence-bank-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sequence-bank-db-credentials
                  key: password
          volumeMounts:
            - name: sequence-bank-db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: sequence-bank-db-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sequence-bank-db
  name: sequence-bank-db
  namespace: mydnacodes
spec:
  type: ClusterIP
  ports:
    - port: 25432
      protocol: TCP
      targetPort: db-port
  selector:
    app: sequence-bank-db-app