apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequence-bank-db-app{{ENV_SUFFIX}}
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: sequence-bank-db-app{{ENV_SUFFIX}}
  replicas: 1
  template:
    metadata:
      labels:
        app: sequence-bank-db-app{{ENV_SUFFIX}}
    spec:
      containers:
        - name: postgres
          image: postgres:12
          ports:
            - name: db-port
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sequence-bank{{ENV_SUFFIX}}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sequence-bank-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sequence-bank-db-credentials
                  key: password
          volumeMounts:
            - name: sequence-bank-db-volume{{ENV_SUFFIX}}
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: sequence-bank-db-volume{{ENV_SUFFIX}}
---
apiVersion: v1
kind: Service
metadata:
  name: sequence-bank-db{{ENV_SUFFIX}}
  namespace: {{NAMESPACE}}
  labels:
    app: sequence-bank-db{{ENV_SUFFIX}}
spec:
  type: ClusterIP
  ports:
    - port: {{DATABASE_PORT}}
      protocol: TCP
      targetPort: db-port
  selector:
    app: sequence-bank-db-app{{ENV_SUFFIX}}