apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequence-bank-app
  namespace: mydnacodes
spec:
  selector:
    matchLabels:
      app: sequence-bank-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sequence-bank-app
    spec:
      containers:
        - name: sequence-bank-container
          image: mydnacodes/sequence-bank-snapshot:latest
          ports:
            - name: sb-port
              containerPort: 8080
              protocol: TCP
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://sequence-bank-db:5432/sequence-bank
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: postgres
          livenessProbe:
            httpGet:
              path: /health/live
              port: sb-port
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: sb-port
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sequence-bank-service
  namespace: mydnacodes
  labels:
    app: sequence-bank-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: sb-port
  selector:
    app: sequence-bank-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sequence-bank
  namespace: mydnacodes
spec:
  rules:
    - host: sequence-bank.mydna.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sequence-bank-service
                port:
                  number: 8081