apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequence-bank-app
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: sequence-bank-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sequence-bank-app
    spec:
      containers:
        - name: sequence-bank-container
          image: {{IMAGE_NAME}}
          imagePullPolicy: Always
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
          env:
            - name: KUMULUZEE_VERSION
              value: {{VERSION}}
            - name: KUMULUZEE_ENV_NAME
              value: {{ENV_NAME}}
            - name: KUMULUZEE_ENV_PROD
              value: "{{ENV_PROD}}"
            - name: KUMULUZEE_SERVER_BASEURL
              value: https://sequence-bank{{ENV_SUFFIX}}.mydna.codes
            - name: KUMULUZEE_SERVER_HTTP_PORT
              value: "8080"
            - name: KUMULUZEE_OPENAPIMP_SERVERS
              value: https://sequence-bank{{ENV_SUFFIX}}.mydna.codes
            - name: KUMULUZEE_CONFIG_NAMESPACE
              value: env/{{ENV_NAME}}
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd-client.kube-etcd:2379
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://sequence-bank-db:5432/sequence-bank
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sequence-bank-db-credentials
                  key: username
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sequence-bank-db-credentials
                  key: password
            - name: KEYCLOAK_AUTHSERVERURL
              valueFrom:
                secretKeyRef:
                  name: keycloak-config
                  key: url
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: keycloak-config
                  key: realm
            - name: KEYCLOAK_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: keycloak-config
                  key: client-id
            - name: KEYCLOAK_AUTH_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-config
                  key: secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sequence-bank-service
  namespace: {{NAMESPACE}}
  labels:
    app: sequence-bank-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: app-port
      name: rest
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: grpc
  selector:
    app: sequence-bank-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sequence-bank
  namespace: {{NAMESPACE}}
spec:
  rules:
    - host: sequence-bank{{ENV_SUFFIX}}.mydna.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sequence-bank-service
                port:
                  number: 8080