kumuluzee:
  name: sequence-bank
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  dev:
    scan-libraries:
      - rest-lib
  server:
    base-url: http://localhost:8080
    show-server-info: false
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  grpc:
    server:
      http:
        port: 8081
  openapi-mp:
    enabled: true
    servers: http://localhost:8080
    scan:
      packages: codes.mydna.lib, codes.mydna.api
    ui:
      enabled: true
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/sequence-bank-db
      disk-space-health-check:
        type: liveness
        threshold: 100000000
  datasources:
    - jndi-name: jdbc/sequence-bank-db
      connection-url: jdbc:postgresql://localhost:5432/sequence-bank
      username: postgres
      password: postgres
      pool:
        max-size: 20
  migrations:
    enabled: true
    liquibase:
      datasources:
        - jndi-name: jdbc/sequence-bank-db
          changelog: db/db.changelog-master.xml
          startup:
            dropAll: false
            update: true

