kumuluzee:
  name: sequence-bank
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  dev:
    scan-libraries:
      - rest-lib
      - sequence-bank-lib-v1
  server:
    base-url: http://localhost:8080
    show-server-info: false
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count, Content-Type"
  grpc:
    server:
      http:
        port: 8081
  openapi-mp:
    enabled: true
    servers: http://localhost:8080
    ui:
      mapping: /openapi/ui
      enabled: true
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/sequence-bank-db
      disk-space-health-check:
        type: liveness
        threshold: 100000000
  config:
    namespace: env/dev
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  datasources:
    - jndi-name: jdbc/sequence-bank-db
      connection-url: jdbc:postgresql://localhost:5432/sequence-bank
      username: postgres
      password: postgres
      pool:
        max-size: 20
  migrations:
    enabled: true
    liquibase:
      changelogs:
        - jndi-name: jdbc/sequence-bank-db
          file: db/db.changelog-master.xml
          startup:
            drop-all: false
            update: true

keycloak:
  realm: not_set
  auth-server-url: not_set
  client-id: not_set
  auth:
    client-secret: not_set

mydnacodes:
  thresholds:
    large-scale:
      min-seq-length: 100000
  limits:
    guest:
      max-dna-length: -1
      max-gene-length: -1
      max-enzyme-length: -1
    reg:
      max-dna-length: -1
      max-gene-length: -1
      max-enzyme-length: -1
    pro:
      max-dna-length: -1
      max-gene-length: -1
      max-enzyme-length: -1