kumuluzee:
  name: sequence-bank
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  openapi:
    enabled: true
    ui:
      enabled: true
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/sequence-bank-db
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/sequence-bank-db
      connection-url: jdbc:postgresql://localhost:65432/sequence-bank
      username: postgres
      password: postgres
      pool:
        max-size: 20
  migrations:
    enabled: true
    liquibase:
      datasources:
        - jndi-name: jdbc/sequence-bank-db
          changelog: db/db.changelog-master.xml
          startup:
            dropAll: false
            update: true

